### ISSUE TITLE
Pronunciation

### ISSUE THREAD

**Issue by iver56** [drscotthawley/aeiou#1]
I like the name, but how do you pronounce it? Some projects mention in readme how to pronounce the name

**Comment by drscotthawley** [comment]
Hey iver!  Honored that you'd ask.  In fact, I have an answer: "ayoo". 
Originally I was pronouncing each letter "a-e-i-o-u", but @zqevans said the name reminded him of [this video](https://www.youtube.com/watch?v=Hv6RbEOlqRo) and I decided, that's it! That's how we'll say it.  
I'll update the README in a little while.

**Comment by iver56** [comment]
Cool, I like it :) At some point I thought "awe" (as in awesome and audio) also could be an alternative

**Comment by drscotthawley** [comment]
Docs and README now include the pronunciation.  Closing.

**Comment by drscotthawley** [comment]
Ivar,
I'm honored that you asked!
I had been saying "a-e-i-o-u" before Zach Evans said it reminded him of this video:
https://www.youtube.com/watch?v=Hv6RbEOlqRo

After which I said, "That's it! The official pronunciation shall be 'ayoo'!"
Lol
I will add it to the README.



On Aug 17, 2022, at 8:20 AM, Iver Jordal ***@***.***> wrote:

﻿

I like the name, but how do you pronounce it? Some projects mention in readme how to pronounce the name
